version: '3.9.6'

services:
  database:
    image: 'postgres:16.1-alpine'
    hostname: postgres
    restart: always
    container_name: step-squad-platform-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  maildev:
    image: maildev/maildev
    ports:
      - '1080:1080'
      - '1025:1025'
    volumes:
      - ./maildev-data:/home/maildev/data
    command: bin/maildev --mail-directory /home/maildev/data
